#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Load the profile.
#
if [ -f $HOME/.zprofile ]; then
  source $HOME/.zprofile;
fi

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Source powerline.
if [ -f ~/.local/lib/python2.7/site-packages/powerline/bindings/zsh/powerline.zsh ]; then
  source ~/.local/lib/python2.7/site-packages/powerline/bindings/zsh/powerline.zsh;
  $POWERLINE_DAEMON_COMMAND -q
fi

# Source virtualenvwrapper.
if [ -f ~/.local/bin/virtualenvwrapper_lazy.sh ]; then
  source ~/.local/bin/virtualenvwrapper_lazy.sh;
fi

# Source aliases.
for file in ~/.aliases/**/*.sh;
do 
  source $file;
done 

# Make esc more responsive.
export KEYTIMEOUT=1
