#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Source powerline.
source ~/.local/lib/python2.7/site-packages/powerline/bindings/zsh/powerline.zsh

# Source virtualenvwrapper.
source ~/.local/bin/virtualenvwrapper_lazy.sh

# Source aliases.
for file in ~/.aliases/**/*.sh;
do 
  source $file;
done 

# Make esc more responsive.
export KEYTIMEOUT=1
